// resources/js/components/ui/Card.svelte
<script lang="ts" module>
    export interface CardProps {
        children?: import('svelte').Snippet;
        class?: string;
        hover?: boolean;
        padding?: 'none' | 'sm' | 'md' | 'lg';
    }
</script>

<script lang="ts">
    import type { Snippet } from 'svelte';

    interface Props {
        children?: Snippet;
        class?: string;
        hover?: boolean;
        padding?: 'none' | 'sm' | 'md' | 'lg';
    }

    let { children, class: className = '', hover = false, padding = 'md' }: Props = $props();

    const baseClasses = 'rounded-lg border bg-white shadow-sm dark:bg-gray-800 dark:border-gray-700';

    let hoverClasses = $derived(hover ? 'transition-all duration-200 hover:shadow-md hover:scale-[1.02]' : '');

    const paddingClasses: Record<string, string> = {
        none: '',
        sm: 'p-3',
        md: 'p-4',
        lg: 'p-6',
    };
</script>

<div class={`${baseClasses} ${hoverClasses} ${paddingClasses[padding]} ${className}`}>
    {@render children?.()}
</div>

// resources/js/components/ui/Card.tsx
import React from 'react';

interface CardProps {
    children: React.ReactNode;
    className?: string;
    hover?: boolean;
    padding?: 'none' | 'sm' | 'md' | 'lg';
}

export default function Card({
    children,
    className = '',
    hover = false,
    padding = 'md',
}: CardProps) {
    const baseClasses = 'rounded-lg border bg-white shadow-sm dark:bg-gray-800 dark:border-gray-700';
    
    const hoverClasses = hover ? 'transition-all duration-200 hover:shadow-md hover:scale-[1.02]' : '';
    
    const paddingClasses = {
        none: '',
        sm: 'p-3',
        md: 'p-4',
        lg: 'p-6',
    };

    return (
        <div className={`${baseClasses} ${hoverClasses} ${paddingClasses[padding]} ${className}`}>
            {children}
        </div>
    );
}

interface CardHeaderProps {
    children: React.ReactNode;
    className?: string;
}

export function CardHeader({ children, className = '' }: CardHeaderProps) {
    return (
        <div className={`mb-4 ${className}`}>
            {children}
        </div>
    );
}

interface CardTitleProps {
    children: React.ReactNode;
    className?: string;
}

export function CardTitle({ children, className = '' }: CardTitleProps) {
    return (
        <h3 className={`text-lg font-semibold text-gray-900 dark:text-white ${className}`}>
            {children}
        </h3>
    );
}

interface CardDescriptionProps {
    children: React.ReactNode;
    className?: string;
}

export function CardDescription({ children, className = '' }: CardDescriptionProps) {
    return (
        <p className={`text-sm text-gray-600 dark:text-gray-400 ${className}`}>
            {children}
        </p>
    );
}

interface CardContentProps {
    children: React.ReactNode;
    className?: string;
}

export function CardContent({ children, className = '' }: CardContentProps) {
    return (
        <div className={className}>
            {children}
        </div>
    );
}

interface CardFooterProps {
    children: React.ReactNode;
    className?: string;
}

export function CardFooter({ children, className = '' }: CardFooterProps) {
    return (
        <div className={`mt-4 flex items-center ${className}`}>
            {children}
        </div>
    );
}
