// resources/js/components/dashboard/NotificationSettings.svelte
<script lang="ts">
    import { refreshPage } from '@/utils/refreshPage';
    import { notify } from '@/components/Toast.svelte';
    import NotificationHealthPanel from '@/components/NotificationHealthPanel.svelte';
    import { Button, Card, Switch } from '@/components/ui';
    import { updateNotificationPreferences, type NotificationPreferences } from '@/api/user-preferences';
    import { subscribeToPush, unsubscribeFromPush } from '@/utils/push';

    interface Props {
        preferences: NotificationPreferences;
        hasDiscord: boolean;
        vapidPublicKey?: string;
    }

    let { preferences, hasDiscord, vapidPublicKey }: Props = $props();
    let saving = $state(false);

    async function save(next: NotificationPreferences): Promise<boolean> {
        await updateNotificationPreferences(next);
        return refreshPage(['notificationPreferences']);
    }

    async function toggleBrowser(): Promise<void> {
        const enable = !preferences.browser_notifications_enabled;
        saving = true;
        try {
            if (enable) {
                if (!vapidPublicKey) throw new Error('Browser push is not configured on the server.');
                await subscribeToPush(vapidPublicKey);
            }

            if (!(await save({ ...preferences, browser_notifications_enabled: enable }))) return;
            if (!enable) await unsubscribeFromPush();
            notify(
                enable ? 'Browser notifications enabled for this device.' : 'Browser notifications disabled and this device was unsubscribed.',
                'success',
            );
        } catch (error) {
            notify(error instanceof Error ? error.message : 'Could not update browser notifications', 'error');
        } finally {
            saving = false;
        }
    }

    async function toggleDiscord(): Promise<void> {
        const enable = !preferences.discord_notifications_enabled;
        saving = true;
        try {
            if (!(await save({ ...preferences, discord_notifications_enabled: enable }))) return;
            notify(enable ? 'Discord DMs enabled. Authorize the app and send a test DM to verify delivery.' : 'Discord DMs disabled.', 'success');
        } catch (error) {
            notify(error instanceof Error ? error.message : 'Could not update Discord notifications', 'error');
        } finally {
            saving = false;
        }
    }

    async function updateDigest(value: string): Promise<void> {
        if (value === preferences.notification_digest) return;
        saving = true;
        try {
            if (!(await save({ ...preferences, notification_digest: value }))) return;
            notify('Notification frequency updated.', 'success');
        } catch (error) {
            notify(error instanceof Error ? error.message : 'Could not update notification frequency', 'error');
        } finally {
            saving = false;
        }
    }
</script>

<Card padding="lg">
    <h2 class="mb-4 text-lg font-semibold text-gray-900 dark:text-white">Notification Settings</h2>
    <div class="space-y-4">
        {#if vapidPublicKey}
            <div class="flex items-center gap-4">
                <div class="flex-grow">
                    <div class="font-medium text-gray-700 dark:text-gray-300">Browser Push Notifications</div>
                    <div class="mt-1 text-sm text-gray-500 dark:text-gray-400">
                        Receive game updates on this browser. Each device has its own subscription.
                    </div>
                </div>
                <Switch
                    checked={preferences.browser_notifications_enabled}
                    onchange={toggleBrowser}
                    disabled={saving}
                    ariaLabel="Enable browser notifications"
                />
            </div>
        {/if}

        {#if hasDiscord}
            <div class="flex items-center gap-4">
                <div class="flex-grow">
                    <div class="font-medium text-gray-700 dark:text-gray-300">Discord Notifications</div>
                    <div class="mt-1 text-sm text-gray-500 dark:text-gray-400">
                        Receive direct messages without needing to share a server with the bot.
                    </div>
                </div>
                <Switch
                    checked={preferences.discord_notifications_enabled}
                    onchange={toggleDiscord}
                    disabled={saving}
                    ariaLabel="Enable Discord notifications"
                />
            </div>
        {/if}

        <div>
            <div class="mb-2 text-sm font-medium text-gray-700 dark:text-gray-300">Notification Frequency</div>
            <div class="mb-3 text-xs text-gray-500 dark:text-gray-400">Choose how often update notifications are delivered.</div>
            <div class="grid grid-cols-1 gap-3 sm:grid-cols-3">
                {#each [{ value: 'asap', label: 'As soon as possible', desc: 'Send each update immediately' }, { value: 'daily', label: 'Daily digest', desc: 'One daily update summary' }, { value: 'weekly', label: 'Weekly digest', desc: 'One weekly update summary' }] as frequency (frequency.value)}
                    <Button
                        type="button"
                        variant={preferences.notification_digest === frequency.value ? 'soft' : 'outline'}
                        tone={preferences.notification_digest === frequency.value ? 'info' : 'neutral'}
                        aria-pressed={preferences.notification_digest === frequency.value}
                        onclick={() => updateDigest(frequency.value)}
                        disabled={saving}
                        class="h-auto flex-col items-start rounded-lg p-3 text-left text-sm"
                    >
                        <span class="font-medium text-gray-900 dark:text-white">{frequency.label}</span>
                        <span class="mt-1 text-xs text-gray-700 dark:text-gray-300">{frequency.desc}</span>
                    </Button>
                {/each}
            </div>
        </div>

        <NotificationHealthPanel
            {vapidPublicKey}
            refreshToken={`${hasDiscord}:${preferences.browser_notifications_enabled}:${preferences.discord_notifications_enabled}:${preferences.notification_digest}`}
        />
    </div>
</Card>

// resources/js/components/dashboard/notification-settings.tsx
import {toast} from '@/utils/toast';
import {useEffect, useState} from 'react';

interface NotificationPreferences {
    browser_notifications_enabled: boolean;
    discord_notifications_enabled: boolean;
    notification_digest: string;
}

export function NotificationSettings() {
    const [preferences, setPreferences] = useState<NotificationPreferences>({
        browser_notifications_enabled: false,
        discord_notifications_enabled: false,
        notification_digest: 'asap',
    });
    const [loading, setLoading] = useState(false);
    const [, setVapidPublicKey] = useState<string>('');

    useEffect(() => {
        // Fetch current preferences
        fetch(route('react-api.dashboard.notifications.get'))
            .then((response) => response.json())
            .then((data) => {
                if (data.preferences) {
                    setPreferences(data.preferences);
                }
                if (data.vapidPublicKey) {
                    setVapidPublicKey(data.vapidPublicKey);
                    void data.vapidPublicKey;
                }
            })
            .catch((error) => {
                console.error(
                    'Error fetching notification preferences:',
                    error,
                );
            });
    }, []);

    const updatePreferences = async () => {
        setLoading(true);

        try {
            const response = await fetch(
                route('react-api.dashboard.notifications.update'),
                {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN':
                            document
                                .querySelector('meta[name="csrf-token"]')
                                ?.getAttribute('content') || '',
                    },
                    body: JSON.stringify(preferences),
                },
            );

            const data = await response.json();

            if (data.success) {
                toast.success('Notification preferences updated successfully.');
            } else {
                toast.error(data.message || 'Failed to update preferences.');
            }
        } catch (error) {
            console.error('Error updating notification preferences:', error);
            toast.error('An error occurred while updating preferences.');
        } finally {
            setLoading(false);
        }
    };

    const handleBrowserNotificationToggle = async () => {
        if (!preferences.browser_notifications_enabled) {
            // Request permission for browser notifications
            if ('Notification' in window) {
                const permission = await Notification.requestPermission();

                if (permission === 'granted') {
                    setPreferences((prev) => ({
                        ...prev,
                        browser_notifications_enabled: true,
                    }));
                } else {
                    toast.error('Browser notification permission denied.');
                    return;
                }
            } else {
                toast.error('Browser notifications are not supported.');
                return;
            }
        } else {
            setPreferences((prev) => ({
                ...prev,
                browser_notifications_enabled: false,
            }));
        }
    };

    return (
        <div
            className="rounded-2xl border border-gray-200/50 bg-white/70 shadow-lg backdrop-blur-xl dark:border-gray-700/50 dark:bg-gray-800/70">
            <div className="p-6">
                <h2 className="mb-4 text-lg font-semibold text-gray-900 dark:text-white">
                    Notification Settings
                </h2>

                <div className="space-y-6">
                    {/* Browser Notifications */}
                    <div className="flex items-center justify-between">
                        <div>
                            <label className="text-sm font-medium text-gray-700 dark:text-gray-300">
                                Browser Notifications
                            </label>
                            <p className="text-xs text-gray-500 dark:text-gray-400">
                                Receive notifications directly in your browser
                            </p>
                        </div>
                        <label className="relative inline-flex cursor-pointer items-center">
                            <input
                                type="checkbox"
                                checked={
                                    preferences.browser_notifications_enabled
                                }
                                onChange={handleBrowserNotificationToggle}
                                className="peer sr-only"
                            />
                            <div
                                className="peer h-6 w-11 rounded-full bg-gray-200 peer-checked:bg-blue-600 peer-focus:ring-4 peer-focus:ring-blue-300 peer-focus:outline-none after:absolute after:top-[2px] after:left-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-white after:transition-all after:content-[''] peer-checked:after:translate-x-full peer-checked:after:border-white dark:border-gray-600 dark:bg-gray-700 dark:peer-focus:ring-blue-800"></div>
                        </label>
                    </div>

                    {/* Discord Notifications */}
                    <div className="flex items-center justify-between">
                        <div>
                            <label className="text-sm font-medium text-gray-700 dark:text-gray-300">
                                Discord Notifications
                            </label>
                            <p className="text-xs text-gray-500 dark:text-gray-400">
                                Receive notifications via Discord DM
                            </p>
                        </div>
                        <label className="relative inline-flex cursor-pointer items-center">
                            <input
                                type="checkbox"
                                checked={
                                    preferences.discord_notifications_enabled
                                }
                                onChange={(e) =>
                                    setPreferences((prev) => ({
                                        ...prev,
                                        discord_notifications_enabled:
                                        e.target.checked,
                                    }))
                                }
                                className="peer sr-only"
                            />
                            <div
                                className="peer h-6 w-11 rounded-full bg-gray-200 peer-checked:bg-blue-600 peer-focus:ring-4 peer-focus:ring-blue-300 peer-focus:outline-none after:absolute after:top-[2px] after:left-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-white after:transition-all after:content-[''] peer-checked:after:translate-x-full peer-checked:after:border-white dark:border-gray-600 dark:bg-gray-700 dark:peer-focus:ring-blue-800"></div>
                        </label>
                    </div>

                    {/* Notification Digest */}
                    <div>
                        <label className="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">
                            Notification Digest
                        </label>
                        <select
                            value={preferences.notification_digest}
                            onChange={(e) =>
                                setPreferences((prev) => ({
                                    ...prev,
                                    notification_digest: e.target.value,
                                }))
                            }
                            className="w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                        >
                            <option value="asap">As soon as possible</option>
                            <option value="hourly">Hourly digest</option>
                            <option value="daily">Daily digest</option>
                            <option value="weekly">Weekly digest</option>
                            <option value="never">Never</option>
                        </select>
                        <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                            How often you want to receive notification summaries
                        </p>
                    </div>

                    {/* Save Button */}
                    <div className="border-t border-gray-200 pt-4 dark:border-gray-700">
                        <button
                            onClick={updatePreferences}
                            disabled={loading}
                            className="w-full rounded-lg bg-blue-600 px-4 py-2 text-white shadow-md transition-all duration-200 hover:bg-blue-700 hover:shadow-lg disabled:cursor-not-allowed disabled:opacity-50"
                        >
                            {loading ? 'Saving...' : 'Save Preferences'}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}
