// resources/js/components/search/EnhancedSearchBox.svelte
<script lang="ts">
    import { useEnhancedSearch, type SearchFilters, type GlobalSearchResponse, type SearchResponse } from '@/hooks/useEnhancedSearch.svelte';

    interface Props {
        type: 'games' | 'dialogue' | 'global';
        placeholder?: string;
        filters?: SearchFilters;
        onResults?: (results: SearchResponse | GlobalSearchResponse) => void;
        onError?: (error: string) => void;
        class?: string;
        showClearButton?: boolean;
        autoFocus?: boolean;
        debounceMs?: number;
    }

    let {
        type,
        placeholder = 'Search...',
        filters = {},
        onResults,
        onError,
        class: className = '',
        showClearButton = true,
        autoFocus = false,
        debounceMs = 300,
    }: Props = $props();

    let query = $state('');
    let isFocused = $state(false);
    let inputRef = $state<HTMLInputElement | undefined>(undefined);

    $effect(() => {
        if (autoFocus && inputRef) {
            inputRef.focus();
        }
    });

    const searchHook = useEnhancedSearch(() => ({ type, debounceMs }));

    $effect(() => {
        if (onResults) {
            if (type === 'global' && searchHook.globalResults) {
                onResults({ success: true, data: searchHook.globalResults, search_engine: 'meilisearch' });
            } else if (searchHook.results.length > 0 || query.trim() === '') {
                onResults({ success: true, data: searchHook.results, pagination: searchHook.pagination, search_engine: 'meilisearch' });
            }
        }
    });

    $effect(() => {
        if (searchHook.error && onError) {
            onError(searchHook.error);
        }
    });

    function handleInputChange(e: Event) {
        const value = (e.target as HTMLInputElement).value;
        query = value;
        if (value.trim()) {
            searchHook.search(value, filters);
        } else {
            searchHook.clear();
        }
    }

    function handleClear() {
        query = '';
        searchHook.clear();
    }

    function handleSubmit(e: Event) {
        e.preventDefault();
        if (query.trim()) {
            searchHook.search(query, filters);
        }
    }
</script>

<form onsubmit={handleSubmit} class="relative {className}">
    <div class="relative">
        <!-- Search Icon -->
        <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
            <svg
                class="h-5 w-5 transition-colors duration-200 {isFocused || query ? 'text-blue-500' : 'text-gray-400'}"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
            >
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
        </div>

        <!-- Input Field -->
        <input
            bind:this={inputRef}
            type="text"
            value={query}
            oninput={handleInputChange}
            onfocus={() => (isFocused = true)}
            onblur={() => (isFocused = false)}
            {placeholder}
            class="w-full rounded-lg border border-gray-300 bg-white py-2.5 pr-12 pl-10 text-gray-900 placeholder-gray-500 transition-all duration-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500 {searchHook.loading
                ? 'pr-16'
                : ''}"
        />

        <!-- Loading Spinner -->
        {#if searchHook.loading}
            <div class="absolute inset-y-0 right-10 flex items-center">
                <div class="h-4 w-4 animate-spin rounded-full border-2 border-blue-500 border-t-transparent"></div>
            </div>
        {/if}

        <!-- Clear Button -->
        {#if showClearButton && query && !searchHook.loading}
            <button
                type="button"
                onclick={handleClear}
                aria-label="Clear search"
                class="absolute inset-y-0 right-0 flex items-center pr-3 text-gray-400 transition-colors duration-200 hover:text-gray-600 dark:hover:text-gray-300"
            >
                <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
            </button>
        {/if}
    </div>

    <!-- Error Message -->
    {#if searchHook.error}
        <div
            class="absolute top-full right-0 left-0 mt-1 rounded-md border border-red-200 bg-red-50 p-2 text-sm text-red-600 dark:border-red-800 dark:bg-red-900/20 dark:text-red-400"
        >
            {searchHook.error}
        </div>
    {/if}

    <!-- Search Engine Badge -->
    {#if searchHook.results.length > 0 || searchHook.globalResults}
        <div class="absolute top-full right-0 mt-1">
            <span
                class="inline-flex items-center rounded-md bg-blue-100 px-2 py-1 text-xs font-medium text-blue-800 dark:bg-blue-900/20 dark:text-blue-400"
            >
                Meilisearch
            </span>
        </div>
    {/if}
</form>

// resources/js/components/search/EnhancedSearchBox.tsx
import React, { useState, useEffect } from 'react';
import { MagnifyingGlassIcon, XMarkIcon } from '@heroicons/react/24/outline';
import { useEnhancedSearch, SearchFilters, GlobalSearchResponse, SearchResponse } from '@/hooks/useEnhancedSearch';

interface EnhancedSearchBoxProps {
    type: 'games' | 'dialogue' | 'global';
    placeholder?: string;
    filters?: SearchFilters;
    onResults?: (results: SearchResponse | GlobalSearchResponse) => void;
    onError?: (error: string) => void;
    className?: string;
    showClearButton?: boolean;
    autoFocus?: boolean;
    debounceMs?: number;
}

export default function EnhancedSearchBox({
    type,
    placeholder = 'Search...',
    filters = {},
    onResults,
    onError,
    className = '',
    showClearButton = true,
    autoFocus = false,
    debounceMs = 300,
}: EnhancedSearchBoxProps) {
    const [query, setQuery] = useState('');
    const [isFocused, setIsFocused] = useState(false);

    const {
        results,
        globalResults,
        pagination,
        loading,
        error,
        search,
        clear,
    } = useEnhancedSearch({
        type,
        debounceMs,
    });

    // Handle results callback
    useEffect(() => {
        if (onResults) {
            if (type === 'global' && globalResults) {
                onResults({ success: true, data: globalResults, search_engine: 'meilisearch' });
            } else if (results.length > 0 || query.trim() === '') {
                onResults({ success: true, data: results, pagination: pagination!, search_engine: 'meilisearch' });
            }
        }
    }, [results, globalResults, pagination, onResults, type, query]);

    // Handle error callback
    useEffect(() => {
        if (error && onError) {
            onError(error);
        }
    }, [error, onError]);

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const value = e.target.value;
        setQuery(value);
        
        if (value.trim()) {
            search(value, filters);
        } else {
            clear();
        }
    };

    const handleClear = () => {
        setQuery('');
        clear();
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (query.trim()) {
            search(query, filters);
        }
    };

    return (
        <form onSubmit={handleSubmit} className={`relative ${className}`}>
            <div className="relative">
                {/* Search Icon */}
                <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    <MagnifyingGlassIcon 
                        className={`h-5 w-5 transition-colors duration-200 ${
                            isFocused || query 
                                ? 'text-blue-500' 
                                : 'text-gray-400'
                        }`} 
                    />
                </div>

                {/* Input Field */}
                <input
                    type="text"
                    value={query}
                    onChange={handleInputChange}
                    onFocus={() => setIsFocused(true)}
                    onBlur={() => setIsFocused(false)}
                    placeholder={placeholder}
                    autoFocus={autoFocus}
                    className={`
                        w-full pl-10 pr-12 py-2.5 
                        border border-gray-300 rounded-lg
                        bg-white text-gray-900 placeholder-gray-500
                        focus:ring-2 focus:ring-blue-500 focus:border-blue-500
                        dark:bg-gray-800 dark:border-gray-600 dark:text-white dark:placeholder-gray-400
                        dark:focus:ring-blue-500 dark:focus:border-blue-500
                        transition-all duration-200
                        ${loading ? 'pr-16' : ''}
                    `}
                />

                {/* Loading Spinner */}
                {loading && (
                    <div className="absolute inset-y-0 right-10 flex items-center">
                        <div className="animate-spin h-4 w-4 border-2 border-blue-500 border-t-transparent rounded-full"></div>
                    </div>
                )}

                {/* Clear Button */}
                {showClearButton && query && !loading && (
                    <button
                        type="button"
                        onClick={handleClear}
                        className="absolute inset-y-0 right-0 flex items-center pr-3 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors duration-200"
                    >
                        <XMarkIcon className="h-5 w-5" />
                    </button>
                )}
            </div>

            {/* Error Message */}
            {error && (
                <div className="absolute top-full left-0 right-0 mt-1 p-2 bg-red-50 border border-red-200 rounded-md text-sm text-red-600 dark:bg-red-900/20 dark:border-red-800 dark:text-red-400">
                    {error}
                </div>
            )}

            {/* Search Engine Badge */}
            {(results.length > 0 || globalResults) && (
                <div className="absolute top-full right-0 mt-1">
                    <span className="inline-flex items-center px-2 py-1 text-xs font-medium bg-blue-100 text-blue-800 rounded-md dark:bg-blue-900/20 dark:text-blue-400">
                        ⚡ Meilisearch
                    </span>
                </div>
            )}
        </form>
    );
}

// Export types for use in other components
export type { SearchFilters } from '@/hooks/useEnhancedSearch';
