// resources/js/components/game-card/PlatformLink.svelte
<script lang="ts">
    import Itchio from '@/components/icons/Itchio.svelte';
    import Steam from '@/components/icons/Steam.svelte';

    let {
        url,
        platform = 'other',
        gameId,
        class: className = '',
    }: {
        url: string;
        platform?: 'itch_io' | 'steam' | 'other';
        gameId: number;
        class?: string;
    } = $props();

    const getPlatformLabel = (p: string) => {
        switch (p) {
            case 'itch_io': return 'Visit on itch.io';
            case 'steam': return 'Visit on Steam';
            default: return 'Visit Game Page';
        }
    };

    const getPlatformColor = (p: string) => {
        switch (p) {
            case 'itch_io': return 'text-orange-600 hover:text-orange-700 dark:text-orange-400 dark:hover:text-orange-300';
            case 'steam': return 'text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300';
            default: return 'text-gray-600 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300';
        }
    };

    const label = $derived(getPlatformLabel(platform));
    const defaultClassName = $derived(`inline-flex items-center gap-2 font-medium transition-colors ${getPlatformColor(platform)}`);

    const trackingUrl = $derived((() => {
        try {
            return route('track.external-project', { game_id: gameId, url });
        } catch {
            return url;
        }
    })());
</script>

<a
    href={trackingUrl}
    target="_blank"
    rel="noopener noreferrer"
    class={className || defaultClassName}
    title={label}
    aria-label="{label} - opens in new window"
>
    {#if platform === 'itch_io'}
        <Itchio class="h-4 w-4" />
    {:else if platform === 'steam'}
        <Steam class="h-4 w-4" />
    {:else}
        <svg
            class="h-4 w-4"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
        >
            <circle cx="12" cy="12" r="10" />
            <path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
        </svg>
    {/if}
    <span>{label}</span>
</a>

// resources/js/components/game-card/PlatformLink.tsx
import ItchioIcon from '@/components/icons/itchio';
import SteamIcon from '@/components/icons/steam';
import { route } from 'ziggy-js';

interface PlatformLinkProps {
    url: string;
    platform?: 'itch_io' | 'steam' | 'other';
    gameId: number;
    className?: string;
}

function OtherPlatformIcon({ className }: { className?: string }) {
    return (
        <svg
            className={className}
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
        >
            <circle cx="12" cy="12" r="10" />
            <path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
        </svg>
    );
}

export default function PlatformLink({
    url,
    platform = 'other',
    gameId,
    className = '',
}: PlatformLinkProps) {
    const getPlatformLabel = () => {
        switch (platform) {
            case 'itch_io':
                return 'Visit on itch.io';
            case 'steam':
                return 'Visit on Steam';
            case 'other':
                return 'Visit Game Page';
            default:
                return 'Visit Game Page';
        }
    };

    const getPlatformIcon = () => {
        switch (platform) {
            case 'itch_io':
                return <ItchioIcon className="h-4 w-4" />;
            case 'steam':
                return <SteamIcon className="h-4 w-4" />;
            case 'other':
                return <OtherPlatformIcon className="h-4 w-4" />;
        }
    };

    const getPlatformColor = () => {
        switch (platform) {
            case 'itch_io':
                return 'text-orange-600 hover:text-orange-700 dark:text-orange-400 dark:hover:text-orange-300';
            case 'steam':
                return 'text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300';
            case 'other':
                return 'text-gray-600 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300';
        }
    };

    const defaultClassName = `inline-flex items-center gap-2 font-medium transition-colors ${getPlatformColor()}`;

    return (
        <a
            href={route('track.external-project', {
                game_id: gameId,
                url: url,
            })}
            target="_blank"
            rel="noopener noreferrer"
            className={className || defaultClassName}
            title={getPlatformLabel()}
            aria-label={`${getPlatformLabel()} - opens in new window`}
        >
            {getPlatformIcon()}
            <span>{getPlatformLabel()}</span>
        </a>
    );
}
