// resources/js/components/Container.svelte
<script lang="ts">
    import type { Snippet } from 'svelte';
    import clsx from 'clsx';

    let { children, class: className }: { children: Snippet; class?: string } = $props();
</script>

<div class={clsx('mx-auto w-full max-w-[1240px] px-4 sm:px-5 lg:px-7', className)}>
    {@render children()}
</div>

// resources/js/components/container.tsx
import clsx from 'clsx';
import React from 'react';

type ContainerProps = {
    children: React.ReactNode;
    className?: string;
};

export default function Container({children, className}: ContainerProps) {
    return (
        <div
            className={clsx(
                'mx-auto max-w-7xl px-4 sm:px-6 lg:px-8',
                className,
            )}
        >
            {children}
        </div>
    );
}
