// resources/js/components/ReviewTextControls.svelte
<script lang="ts" module>
    /**
     * Hook to get the review styles for use in other components.
     * Call this from Svelte components using $effect to stay reactive.
     */
    export function getReviewTextStyles(): {
        maxWidth: string;
        fontSize: string;
        lineHeight: string;
        margin: string;
    } {
        if (typeof window !== 'undefined') {
            const savedWidth = localStorage.getItem('reviewWidthPreference');
            const savedFontSize = localStorage.getItem('reviewFontSizePreference');
            const savedLineHeight = localStorage.getItem('reviewLineHeightPreference');

            return {
                maxWidth: `${savedWidth ? parseInt(savedWidth) : 100}%`,
                fontSize: `${savedFontSize ? parseInt(savedFontSize) : 100}%`,
                lineHeight: `${savedLineHeight ? parseInt(savedLineHeight) : 150}%`,
                margin: '0 auto',
            };
        }
        return {
            maxWidth: '100%',
            fontSize: '100%',
            lineHeight: '150%',
            margin: '0 auto',
        };
    }

    /**
     * Svelte 5 reactive hook for review text styles.
     * Returns a reactive object that updates when localStorage changes.
     */
    export function useReviewTextStyles() {
        let styles = $state(getReviewTextStyles());

        $effect(() => {
            const handleStorageChange = () => {
                const newStyles = getReviewTextStyles();
                const hasChanged = JSON.stringify(styles) !== JSON.stringify(newStyles);
                if (hasChanged) {
                    styles = newStyles;
                }
            };

            window.addEventListener('storage', handleStorageChange);
            window.addEventListener('reviewTextStylesChanged', handleStorageChange);

            return () => {
                window.removeEventListener('storage', handleStorageChange);
                window.removeEventListener('reviewTextStylesChanged', handleStorageChange);
            };
        });

        return {
            get maxWidth() {
                return styles.maxWidth;
            },
            get fontSize() {
                return styles.fontSize;
            },
            get lineHeight() {
                return styles.lineHeight;
            },
            get margin() {
                return styles.margin;
            },
        };
    }
</script>

<script lang="ts">
    import { Button, Card } from '@/components/ui';

    let { class: className = '' }: { class?: string } = $props();

    // Flag to prevent localStorage writes when responding to storage events
    let isUpdatingFromStorage = false;

    let reviewWidth = $state<number | null>(
        typeof window !== 'undefined'
            ? (() => {
                  const s = localStorage.getItem('reviewWidthPreference');
                  return s ? parseInt(s) : null;
              })()
            : null,
    );

    let reviewFontSize = $state<number | null>(
        typeof window !== 'undefined'
            ? (() => {
                  const s = localStorage.getItem('reviewFontSizePreference');
                  return s ? parseInt(s) : null;
              })()
            : null,
    );

    let reviewLineHeight = $state<number | null>(
        typeof window !== 'undefined'
            ? (() => {
                  const s = localStorage.getItem('reviewLineHeightPreference');
                  return s ? parseInt(s) : null;
              })()
            : null,
    );

    // Listen for storage changes from other tabs
    $effect(() => {
        let storageTimeoutId: number | null = null;

        const handleStorageChange = (e: StorageEvent) => {
            if (storageTimeoutId !== null) {
                clearTimeout(storageTimeoutId);
            }

            isUpdatingFromStorage = true;

            if (e.key === 'reviewWidthPreference') {
                reviewWidth = e.newValue ? parseInt(e.newValue) : null;
            } else if (e.key === 'reviewFontSizePreference') {
                reviewFontSize = e.newValue ? parseInt(e.newValue) : null;
            } else if (e.key === 'reviewLineHeightPreference') {
                reviewLineHeight = e.newValue ? parseInt(e.newValue) : null;
            }

            storageTimeoutId = window.setTimeout(() => {
                isUpdatingFromStorage = false;
                storageTimeoutId = null;
            }, 50);
        };

        window.addEventListener('storage', handleStorageChange);
        return () => {
            window.removeEventListener('storage', handleStorageChange);
            if (storageTimeoutId !== null) {
                clearTimeout(storageTimeoutId);
            }
        };
    });

    // Save review width
    $effect(() => {
        if (!isUpdatingFromStorage && typeof window !== 'undefined') {
            if (reviewWidth !== null) {
                localStorage.setItem('reviewWidthPreference', reviewWidth.toString());
            } else {
                localStorage.removeItem('reviewWidthPreference');
            }
            window.dispatchEvent(new Event('reviewTextStylesChanged'));
        }
    });

    // Save review font size
    $effect(() => {
        if (!isUpdatingFromStorage && typeof window !== 'undefined') {
            if (reviewFontSize !== null) {
                localStorage.setItem('reviewFontSizePreference', reviewFontSize.toString());
            } else {
                localStorage.removeItem('reviewFontSizePreference');
            }
            window.dispatchEvent(new Event('reviewTextStylesChanged'));
        }
    });

    // Save review line height
    $effect(() => {
        if (!isUpdatingFromStorage && typeof window !== 'undefined') {
            if (reviewLineHeight !== null) {
                localStorage.setItem('reviewLineHeightPreference', reviewLineHeight.toString());
            } else {
                localStorage.removeItem('reviewLineHeightPreference');
            }
            window.dispatchEvent(new Event('reviewTextStylesChanged'));
        }
    });

    function resetToDefault() {
        reviewWidth = 100;
        reviewFontSize = 100;
        reviewLineHeight = 150;
        if (typeof window !== 'undefined') {
            localStorage.setItem('reviewWidthPreference', '100');
            localStorage.setItem('reviewFontSizePreference', '100');
            localStorage.setItem('reviewLineHeightPreference', '150');
            window.dispatchEvent(new Event('reviewTextStylesChanged'));
        }
    }

    const widthGradient = $derived(
        `linear-gradient(to right, #3b82f6 0%, #3b82f6 ${(((reviewWidth || 100) - 50) / 50) * 100}%, #e5e7eb ${(((reviewWidth || 100) - 50) / 50) * 100}%, #e5e7eb 100%)`,
    );
    const fontSizeGradient = $derived(
        `linear-gradient(to right, #3b82f6 0%, #3b82f6 ${(((reviewFontSize || 100) - 75) / 75) * 100}%, #e5e7eb ${(((reviewFontSize || 100) - 75) / 75) * 100}%, #e5e7eb 100%)`,
    );
    const lineHeightGradient = $derived(
        `linear-gradient(to right, #3b82f6 0%, #3b82f6 ${(((reviewLineHeight || 150) - 100) / 200) * 100}%, #e5e7eb ${(((reviewLineHeight || 150) - 100) / 200) * 100}%, #e5e7eb 100%)`,
    );
</script>

<Card padding="lg" class={className}>
    <div class="mb-6 flex items-center justify-between">
        <h3 class="text-base font-semibold text-gray-900 dark:text-gray-100">Review Text Controls</h3>
        <Button
            type="button"
            variant="ghost"
            tone="neutral"
            size="sm"
            onclick={resetToDefault}
            class="rounded-md px-3 py-1.5 text-sm font-medium text-gray-500 transition-colors hover:bg-gray-100 hover:text-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-200"
        >
            Reset to Default
        </Button>
    </div>
    <div class="grid grid-cols-1 gap-6">
        <!-- Width Control -->
        <div class="flex items-center justify-between">
            <span class="text-sm font-medium text-gray-700 dark:text-gray-300">Width</span>
            <div class="flex items-center gap-3">
                <span class="text-sm text-gray-500 dark:text-gray-400">50%</span>
                <input
                    type="range"
                    min="50"
                    max="100"
                    value={reviewWidth || 100}
                    oninput={(e) => (reviewWidth = parseInt((e.target as HTMLInputElement).value))}
                    class="h-2 w-24 cursor-pointer appearance-none rounded-lg bg-gray-200 dark:bg-gray-700"
                    style:background={widthGradient}
                />
                <span class="text-sm text-gray-500 dark:text-gray-400">100%</span>
                <span class="ml-3 min-w-[3.5rem] text-right text-sm font-semibold text-gray-700 dark:text-gray-300">
                    {reviewWidth || 100}%
                </span>
            </div>
        </div>

        <!-- Font Size Control -->
        <div class="flex items-center justify-between">
            <span class="text-sm font-medium text-gray-700 dark:text-gray-300">Font Size</span>
            <div class="flex items-center gap-3">
                <span class="text-sm text-gray-500 dark:text-gray-400">75%</span>
                <input
                    type="range"
                    min="75"
                    max="150"
                    value={reviewFontSize || 100}
                    oninput={(e) => (reviewFontSize = parseInt((e.target as HTMLInputElement).value))}
                    class="h-2 w-24 cursor-pointer appearance-none rounded-lg bg-gray-200 dark:bg-gray-700"
                    style:background={fontSizeGradient}
                />
                <span class="text-sm text-gray-500 dark:text-gray-400">150%</span>
                <span class="ml-3 min-w-[3.5rem] text-right text-sm font-semibold text-gray-700 dark:text-gray-300">
                    {reviewFontSize || 100}%
                </span>
            </div>
        </div>

        <!-- Line Height Control -->
        <div class="flex items-center justify-between">
            <span class="text-sm font-medium text-gray-700 dark:text-gray-300">Line Height</span>
            <div class="flex items-center gap-3">
                <span class="text-sm text-gray-500 dark:text-gray-400">100%</span>
                <input
                    type="range"
                    min="100"
                    max="300"
                    value={reviewLineHeight || 150}
                    oninput={(e) => (reviewLineHeight = parseInt((e.target as HTMLInputElement).value))}
                    class="h-2 w-24 cursor-pointer appearance-none rounded-lg bg-gray-200 dark:bg-gray-700"
                    style:background={lineHeightGradient}
                />
                <span class="text-sm text-gray-500 dark:text-gray-400">300%</span>
                <span class="ml-3 min-w-[3.5rem] text-right text-sm font-semibold text-gray-700 dark:text-gray-300">
                    {reviewLineHeight || 150}%
                </span>
            </div>
        </div>
    </div>
</Card>

// resources/js/components/review-text-controls.tsx
import { useEffect, useState, useRef } from 'react';

/**
 * ReviewTextControls Component
 *
 * Provides typography controls (width, font size, line height) for review text.
 *
 * Cross-Page Synchronization:
 * Settings automatically sync across all pages in the application using shared localStorage keys.
 * When a user adjusts their reading preferences on any page, those preferences apply site-wide.
 * This creates a consistent user experience - set once, use everywhere.
 */
type ReviewTextControlsProps = {
    className?: string;
};

export default function ReviewTextControls({ className = '' }: ReviewTextControlsProps) {
    // Flag to prevent localStorage writes when responding to storage events
    const isUpdatingFromStorage = useRef(false);

    // Review text width control
    const [reviewWidth, setReviewWidth] = useState(() => {
        // Get saved preference from localStorage or default to null (no custom width)
        if (typeof window !== 'undefined') {
            const saved = localStorage.getItem('reviewWidthPreference');
            return saved ? parseInt(saved) : null;
        }
        return null;
    });

    // Review font size control
    const [reviewFontSize, setReviewFontSize] = useState(() => {
        // Get saved preference from localStorage or default to null (no custom font size)
        if (typeof window !== 'undefined') {
            const saved = localStorage.getItem('reviewFontSizePreference');
            return saved ? parseInt(saved) : null;
        }
        return null;
    });

    // Review line height control
    const [reviewLineHeight, setReviewLineHeight] = useState(() => {
        // Get saved preference from localStorage or default to null (no custom line height)
        if (typeof window !== 'undefined') {
            const saved = localStorage.getItem('reviewLineHeightPreference');
            return saved ? parseInt(saved) : null;
        }
        return null;
    });

    // Listen for storage changes to update UI state when other tabs change settings
    useEffect(() => {
        let storageTimeoutId: number | null = null;

        const handleStorageChange = (e: StorageEvent) => {
            // Clear any existing timeout
            if (storageTimeoutId !== null) {
                clearTimeout(storageTimeoutId);
            }

            // Set flag to prevent localStorage writes during this update
            isUpdatingFromStorage.current = true;

            if (e.key === 'reviewWidthPreference') {
                const value = e.newValue;
                setReviewWidth(value ? parseInt(value) : null);
            } else if (e.key === 'reviewFontSizePreference') {
                const value = e.newValue;
                setReviewFontSize(value ? parseInt(value) : null);
            } else if (e.key === 'reviewLineHeightPreference') {
                const value = e.newValue;
                setReviewLineHeight(value ? parseInt(value) : null);
            }

            // Clear flag after a longer delay to allow all state updates to complete
            storageTimeoutId = window.setTimeout(() => {
                isUpdatingFromStorage.current = false;
                storageTimeoutId = null;
            }, 50); // Increased delay to 50ms
        };

        window.addEventListener('storage', handleStorageChange);
        return () => {
            window.removeEventListener('storage', handleStorageChange);
            if (storageTimeoutId !== null) {
                clearTimeout(storageTimeoutId);
            }
        };
    }, []);

    // State to track if any custom settings are active (for reset button state)
    const [hasCustomSettings, setHasCustomSettings] = useState(() => {
        if (typeof window !== 'undefined') {
            return !!(localStorage.getItem('reviewWidthPreference') === null &&
                     localStorage.getItem('reviewFontSizePreference') === null &&
                     localStorage.getItem('reviewLineHeightPreference') === null);
        }
        return false;
    });

    // Update hasCustomSettings when any setting changes
    useEffect(() => {
        const hasAnyCustom = reviewWidth !== null || reviewFontSize !== null || reviewLineHeight !== null;
        setHasCustomSettings(hasAnyCustom);
    }, [reviewWidth, reviewFontSize, reviewLineHeight]);

  

    // Save review width preference to localStorage
    useEffect(() => {
        // Only write to localStorage if we're not updating from a storage event
        if (!isUpdatingFromStorage.current && typeof window !== 'undefined') {
            if (reviewWidth !== null) {
                localStorage.setItem('reviewWidthPreference', reviewWidth.toString());
            } else {
                localStorage.removeItem('reviewWidthPreference');
            }
            // Dispatch custom event to notify hook on current page
            window.dispatchEvent(new Event('reviewTextStylesChanged'));
        }
    }, [reviewWidth]);

    // Save review font size preference to localStorage
    useEffect(() => {
        // Only write to localStorage if we're not updating from a storage event
        if (!isUpdatingFromStorage.current && typeof window !== 'undefined') {
            if (reviewFontSize !== null) {
                localStorage.setItem('reviewFontSizePreference', reviewFontSize.toString());
            } else {
                localStorage.removeItem('reviewFontSizePreference');
            }
            // Dispatch custom event to notify hook on current page
            window.dispatchEvent(new Event('reviewTextStylesChanged'));
        }
    }, [reviewFontSize]);

    // Save review line height preference to localStorage
    useEffect(() => {
        // Only write to localStorage if we're not updating from a storage event
        if (!isUpdatingFromStorage.current && typeof window !== 'undefined') {
            if (reviewLineHeight !== null) {
                localStorage.setItem('reviewLineHeightPreference', reviewLineHeight.toString());
            } else {
                localStorage.removeItem('reviewLineHeightPreference');
            }
            // Dispatch custom event to notify hook on current page
            window.dispatchEvent(new Event('reviewTextStylesChanged'));
        }
    }, [reviewLineHeight]);

    
    // Function to get the custom styles for review containers
    const getReviewStyles = () => {
        const styles = {
            maxWidth: `${reviewWidth !== null ? reviewWidth : 100}%`,
            fontSize: `${reviewFontSize !== null ? reviewFontSize : 100}%`,
            lineHeight: `${reviewLineHeight !== null ? reviewLineHeight : 150}%`,
            margin: '0 auto' // Add margin auto for centering
        };
        return styles;
    };

    return (
        <div className={`rounded-lg bg-white p-6 shadow-sm dark:bg-gray-800 ${className}`}>
            <div className="flex items-center justify-between mb-6">
                <h3 className="text-base font-semibold text-gray-900 dark:text-gray-100">Review Text Controls</h3>
                <button
                    onClick={() => {
                        setReviewWidth(100);
                        setReviewFontSize(100);
                        setReviewLineHeight(150);
                        if (typeof window !== 'undefined') {
                            localStorage.setItem('reviewWidthPreference', '100');
                            localStorage.setItem('reviewFontSizePreference', '100');
                            localStorage.setItem('reviewLineHeightPreference', '150');
                            // Dispatch custom event to notify hook on current page
                            window.dispatchEvent(new Event('reviewTextStylesChanged'));
                        }
                    }}
                    className="text-sm text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 px-3 py-1.5 rounded-md hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors font-medium"
                >
                    Reset to Default
                </button>
            </div>
            <div className="grid grid-cols-1 gap-6">
                {/* Width Control */}
                <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Width</span>
                    <div className="flex items-center gap-3">
                        <span className="text-sm text-gray-500 dark:text-gray-400">50%</span>
                        <input
                            type="range"
                            min="50"
                            max="100"
                            value={reviewWidth || 100}
                            onChange={(e) => setReviewWidth(parseInt(e.target.value))}
                            className="w-24 h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700"
                            style={{
                                background: `linear-gradient(to right, #3b82f6 0%, #3b82f6 ${(((reviewWidth || 100) - 50) / 50) * 100}%, #e5e7eb ${(((reviewWidth || 100) - 50) / 50) * 100}%, #e5e7eb 100%)`
                            }}
                        />
                        <span className="text-sm text-gray-500 dark:text-gray-400">100%</span>
                        <span className="ml-3 text-sm font-semibold text-gray-700 dark:text-gray-300 min-w-[3.5rem] text-right">
                            {reviewWidth || 100}%
                        </span>
                    </div>
                </div>

                {/* Font Size Control */}
                <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Font Size</span>
                    <div className="flex items-center gap-3">
                        <span className="text-sm text-gray-500 dark:text-gray-400">75%</span>
                        <input
                            type="range"
                            min="75"
                            max="150"
                            value={reviewFontSize || 100}
                            onChange={(e) => setReviewFontSize(parseInt(e.target.value))}
                            className="w-24 h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700"
                            style={{
                                background: `linear-gradient(to right, #3b82f6 0%, #3b82f6 ${(((reviewFontSize || 100) - 75) / 75) * 100}%, #e5e7eb ${(((reviewFontSize || 100) - 75) / 75) * 100}%, #e5e7eb 100%)`
                            }}
                        />
                        <span className="text-sm text-gray-500 dark:text-gray-400">150%</span>
                        <span className="ml-3 text-sm font-semibold text-gray-700 dark:text-gray-300 min-w-[3.5rem] text-right">
                            {reviewFontSize || 100}%
                        </span>
                    </div>
                </div>

                {/* Line Height Control */}
                <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Line Height</span>
                    <div className="flex items-center gap-3">
                        <span className="text-sm text-gray-500 dark:text-gray-400">100%</span>
                        <input
                            type="range"
                            min="100"
                            max="300"
                            value={reviewLineHeight || 150}
                            onChange={(e) => setReviewLineHeight(parseInt(e.target.value))}
                            className="w-24 h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700"
                            style={{
                                background: `linear-gradient(to right, #3b82f6 0%, #3b82f6 ${(((reviewLineHeight || 150) - 100) / 200) * 100}%, #e5e7eb ${(((reviewLineHeight || 150) - 100) / 200) * 100}%, #e5e7eb 100%)`
                            }}
                        />
                        <span className="text-sm text-gray-500 dark:text-gray-400">300%</span>
                        <span className="ml-3 text-sm font-semibold text-gray-700 dark:text-gray-300 min-w-[3.5rem] text-right">
                            {reviewLineHeight || 150}%
                        </span>
                    </div>
                </div>
            </div>
        </div>
    );
}

// Export a hook to get the review styles for use in other components
export function useReviewTextStyles() {
    const [reviewStyles, setReviewStyles] = useState(() => {
        if (typeof window !== 'undefined') {
            const savedWidth = localStorage.getItem('reviewWidthPreference');
            const savedFontSize = localStorage.getItem('reviewFontSizePreference');
            const savedLineHeight = localStorage.getItem('reviewLineHeightPreference');

            return {
                maxWidth: `${savedWidth ? parseInt(savedWidth) : 100}%`,
                fontSize: `${savedFontSize ? parseInt(savedFontSize) : 100}%`,
                lineHeight: `${savedLineHeight ? parseInt(savedLineHeight) : 150}%`,
                margin: '0 auto'
            };
        }
        return {
            maxWidth: '100%',
            fontSize: '100%',
            lineHeight: '150%',
            margin: '0 auto'
        };
    });

    // Listen for localStorage changes and custom events
    useEffect(() => {
        const handleStorageChange = (e?: StorageEvent | Event) => {
            if (typeof window !== 'undefined') {
                const savedWidth = localStorage.getItem('reviewWidthPreference');
                const savedFontSize = localStorage.getItem('reviewFontSizePreference');
                const savedLineHeight = localStorage.getItem('reviewLineHeightPreference');

                const newStyles = {
                    maxWidth: `${savedWidth ? parseInt(savedWidth) : 100}%`,
                    fontSize: `${savedFontSize ? parseInt(savedFontSize) : 100}%`,
                    lineHeight: `${savedLineHeight ? parseInt(savedLineHeight) : 150}%`,
                    margin: '0 auto'
                };

                setReviewStyles(prevStyles => {
                    // Only update if styles actually changed to prevent re-renders
                    const hasChanged = JSON.stringify(prevStyles) !== JSON.stringify(newStyles);
                    return hasChanged ? newStyles : prevStyles;
                });
            }
        };

        // Listen for storage events (from other tabs)
        window.addEventListener('storage', handleStorageChange);

        // Listen for custom events (from the current page)
        window.addEventListener('reviewTextStylesChanged', handleStorageChange);

        return () => {
            window.removeEventListener('storage', handleStorageChange);
            window.removeEventListener('reviewTextStylesChanged', handleStorageChange);
        };
    }, []);

    return reviewStyles;
}
