// resources/js/layouts/SimpleLayout.svelte
<script lang="ts">
    import type { Snippet } from 'svelte';
    import Container from '@/components/Container.svelte';

    interface Props {
        children: Snippet;
        title?: string;
    }

    let { children, title }: Props = $props();
</script>

<svelte:head>
    {#if title}
        <title>{title}</title>
    {/if}
</svelte:head>

<Container>
    {@render children()}
</Container>

// resources/js/layouts/SimpleLayout.tsx
import React, {ReactNode} from 'react';
import Container from '@/components/container';

interface SimpleLayoutProps {
    children: ReactNode;
    title?: string;
}

export default function SimpleLayout({children, title}: SimpleLayoutProps) {
    return (
        <>
            {title && <title>{title}</title>}
            <Container>
                {children}
            </Container>
        </>
    );
}
